name: Update Submodule and build documentation
on:
  push:
    branches:
      - main
      - master
  repository_dispatch:
    types: [submodule_update]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.PAT_TOKEN }}
          
      - name: Git config
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
      - name: Update submodule
        run: |
          cd docs
          git checkout main
          git pull origin main
          cd ..
          git add docs
          
      - name: Commit and push if changed
        run: |
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update docs submodule to latest main"
            git fetch
            git push
          fi
      
  deploy:
      needs: sync
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
          with:
              submodules: true
              token: ${{ secrets.PAT_TOKEN }}
              fetch-depth: 0  # Needed for gh-deploy
        - name: Configure Git Credentials
          run: |
            git config user.name github-actions[bot]
            git config user.email 41898282+github-actions[bot]@users.noreply.github.com
        - uses: actions/setup-python@v5
          with:
            python-version: 3.x
        - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
        - uses: actions/cache@v4
          with:
            key: mkdocs-material-${{ env.cache_id }}
            path: .cache
            restore-keys: |
              mkdocs-material-
        - run: |
            python -m pip install --upgrade pip
            python -m pip install -r prerequisites.txt 
        - run: mkdocs build

        - name: Push to documentation repository
          run: |
            cd site
            git init
            git add -A
            git config user.name github-actions[bot]
            git config user.email 41898282+github-actions[bot]@users.noreply.github.com
            git commit -m "Update documentation"
            git branch -M main
            git remote add origin https://x-access-token:${{ secrets.DOCS_DEPLOY_TOKEN }}@github.com/YePererva/course_site.git
            git push -f origin main